### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by babyasishhira** [ThomasNegeli/M2CliTools#1]
php version 7.1

magento version 2.1

After install the command not found http://prntscr.com/kmb8mo

**Comment by ThomasNegeli** [comment]
Did you upgrade your DB? Check if there is an entry in setup_module table with the value "Tnegeli_M2CliTools".
Did you flush caches?

**Comment by babyasishhira** [comment]
@ThomasNegeli 

Yes I did run setup:upgrade also run cache:clean 

But no idea how that time that command did not work. 

But now it is working very fine. Thank you for this great module

**Comment by ThomasNegeli** [comment]
Thanks for your feedback
