### ISSUE TITLE
please document installation

### ISSUE THREAD

**Issue by YiffyToys** [ThomasNegeli/M2CliTools#16]
The readme.md describes how to use it but not how to install it.

I tried
```
composer config repositories.ThomasNegeli-M2CliTools git "https://github.com/ThomasNegeli/M2CliTools.git"
composer require  ThomasNegeli/M2CliTools
composer require  ThomasNegeli/M2CliTools dev-master 
```
but 
` Could not find a matching version of package ThomasNegeli/M2CliTools. Check the package spelling, your version constraint and that the package is availa
  ble in a stability which matches your minimum-stability (stable).
`

for Magento ver. 2.4.3-p1

**Comment by ThomasNegeli** [comment]
Hi @YiffyToys, nothing special here. You just typed the package name incorrectly in camelcase letters. Composer package names are lowercase. Copy from here: https://github.com/ThomasNegeli/M2CliTools/blob/master/composer.json#L2
