### ISSUE TITLE
Rediscache Issue

### ISSUE THREAD

**Issue by Giriram095** [ThomasNegeli/M2CliTools#2]
When I try to install M2CLI Extension in magento 2 shows an error in Magento 2 While Deploying. 
I have Enabled Rediscache in magento 2

ERROR-1: unserialize(): Error at offset 0 of 2 bytes in vendor/magento/framework/Config/Data/Scoped.php on line 101

**Comment by ThomasNegeli** [comment]
I have various installations of the module in production, mainly with active redis, but also with file caching. 
There is no general issue. 
Which Magento version are you using? Which Redis version?

**Comment by ThomasNegeli** [comment]
Closing due to no feedback
