### ISSUE TITLE
Error "Area code is already set" on setup:upgrade with Magento CE 2.1.6

### ISSUE THREAD

**Issue by shamoon** [ThomasNegeli/M2CliTools#3]
Current version of the plugin causes an error when running setup:upgrade with Magento CE 2.1.6. Seen this issue with other plugins too.

Error is:

> [Magento\Framework\Exception\LocalizedException]  
>   Area code is already set                          
> 

And problem is line 41 of tnegeli/m2clitools/Console/Command/CleanupUnusedSwatchesMedia.php
`$state->setAreaCode( 'frontend' );`

should be replaced with something like
`
try {
    $state->_state->setAreaCode('frontend');
} catch (\Exception $e) {
}
`

**Comment by ThomasNegeli** [comment]
@nikonratm did you try to get the areaCode? Don't like the idea of silently catching an exception.

**Comment by ThomasNegeli** [comment]
2.1.6 is no longer supported by Magento. So testing a possible issue for an old version makes no sense.
