### ISSUE TITLE
Error: 'The helper "table" is not defined. ' when run on magento 2.3.1

### ISSUE THREAD

**Issue by RaFr** [ThomasNegeli/M2CliTools#5]
when i run "bin/magento tnegeli:cleanup-unused-product-media --dry-run i get the error "The helper "table" is not defined."

**Comment by ThomasNegeli** [comment]
I can not reproduce this issue with version 1.3.0 on a fresh installation of Magento 2.3.1.
The error in your case seems to come from this line: https://github.com/ThomasNegeli/M2CliTools/blob/master/Console/Command/CleanupUnusedProductMedia.php#L121
But the table is coming from symfony console, so there must be an issue with your installation. Maybe your autoloader is broken?

**Comment by RaFr** [comment]
could you tell me what autoloader please so i can make some research about it to see how i can check if it is broken and how i can fix it? i have 2 installations on 2 different servers and i got the same behavior on both of them.
thanks

Edit:
it seems that the problem is related to symfony version as "The Table Helper was deprecated in Symfony 2.5 and removed in Symfony 3.0. " 
i tried the following:
i replaced the L121 of the file CleanupUnusedProductMedia.php:
`$this->getHelper( 'table' )
            ->setHeaders( $headers )`
with
`$newtable = new Table($output);
        $newtable  ->setHeaders( $headers )`
and added `use Symfony\Component\Console\Helper\Table;` at the beginning of the page.

the command "bin/magento tnegeli:cleanup-unused-product-media --dry-run" finished without errors

**Comment by danieljoeblack** [comment]
This exact issue is happening to me on M2.3.1 so I think it may be a real issue. 

Making the change suggested by @RaFr seems to have fixed the error, so thanks for the help!
