### ISSUE TITLE
There are no commands defined in the "tnegeli" namespace.

### ISSUE THREAD

**Issue by mincovip** [ThomasNegeli/M2CliTools#7]
Hi there,

Where I run the M2CliTools' command, it returns an error  "There are no commands defined in the "tnegeli" namespace". You can see the below detail.

https://i.ibb.co/f1swYw6/issue.png

Our Magento version:  2.3.1

**Comment by ThomasNegeli** [comment]
Check if the module is enabled in your config.php
clean caches
run di:compile

**Comment by ThomasNegeli** [comment]
Closed due to inactivity
